language: cpp

matrix:
  include:
    - os: linux
      dist: focal
      before-install:
        - sudo apt-get update
        - sudo apt-get -y install g++-10 ninja-build libboost1.71-all-dev libbotan-2-dev swig
        - sudo snap install cmake --classic
        - pip install minecraft_data
      script:
        - "./scripts/linux-build.sh"
