name: Build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2
      - run: pacman --noconfirm -Syu
      - run: pacman --noconfirm -S boost botan python python-pip python-wheel zlib cmake ninja swig
      - run: pip install minecraft-data
      - run: cmake . -G Ninja
      - run: cmake --build . --target rikerbot_all
